version: '3.8'

services:
  home-page:
    build:
      context: .
      dockerfile: Dockerfile
    image: home-page:latest
    container_name: home-page
    ports:
      - "15200:15200"
    networks:
      - kcbjt-net

networks:
  kcbjt-net:
    name: kcbjt-net
    driver: bridge